### PR TITLE
Likes functionality

### PR DESCRIPTION
**Pull request by kart-c**
## Likes Functionality

- Like a video from the home page
- Unlike a video from the home page
- Show liked videos on liked page
- Unlike a video from the home page
- Show the last updated date
- Display liked video thumbnail on liked page

### CODE REVIEW

**Review by Kevin-Solomon — APPROVED** [review]

**Comment by Kevin-Solomon** [comment]
Also, just a nitpick you can add a little bit of padding to the image.
image

**Review by mohammed-sas — APPROVED** [review]

**Review by NamrataRaikwar2002 — APPROVED** [review]
All looks good, one suggestion is that when the modal opens, then clicking outside of the modal, will close it.

 other than this,
- UI looks nice.
- functionality is working properly.
  Great work :+1:

**Comment by kart-c** [comment]
> Also, just a nitpick you can add a little bit of padding to the image. image

I have used `object-fit: cover` since all images can be of different sizes. Thanks for noticing this, maybe I can scale down the image later to resize it to container height and width (since this image comes from local and not database)

**Comment by kart-c** [comment]
> All looks good, one suggestion is that when the modal opens, then clicking outside of the modal, will close it.
> 
> other than this,
> 
> * UI looks nice.
> * functionality is working properly.
>   Great work 👍

This will be done when I add the single video page 👍🏻

**Pull request merged**
